name: Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install -g conventional-changelog-cli

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git tag --sort=-creatordate | head -n 1 || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Bump version (patch) and generate changelog
        id: bump_version
        run: |
          latest_tag="${{ steps.get_tag.outputs.latest_tag }}"
          current_version=$(echo "$latest_tag" | sed 's/^v//')
          IFS='.' read -r major minor patch <<< "$current_version"
          new_version="$major.$minor.$((patch+1))"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

          # Generate changelog
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0

      - name: Commit and tag
        run: |
          git add CHANGELOG.md
          git commit -m "chore(release): v${{ steps.bump_version.outputs.new_version }} [skip ci]"
          git tag -a v${{ steps.bump_version.outputs.new_version }} -m "Release v${{ steps.bump_version.outputs.new_version }}"
          git push origin main --follow-tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.bump_version.outputs.new_version }}
          name: Release v${{ steps.bump_version.outputs.new_version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
